[package]
name = "game-of-chance"
version = "0.3.1"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
parity-scale-codec = { version = "3", default-features = false }
scale-info = { version = "2", default-features = false }
rand = { version = "0.8", default-features = false }
rand_xoshiro = "0.6"
ft-main-io = { git = "https://github.com/gear-dapps/sharded-fungible-token.git", tag = "2.1.0" }
hashbrown = "0.13"
game-of-chance-io = { path = "io" }

[dev-dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet", features = ["debug"] }
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
# TODO: Remove rev(70e6ade) pin, when core-team update `testnet` gear crates
gclient = { git = "https://github.com/gear-tech/gear.git", rev = "70e6ade" }
sp-core-hashing = "8.0.0"
subxt = { version = "0.27", default-features = false }
primitive-types = "0.12"
tokio = "1"
pretty_assertions = "1"

[build-dependencies]
game-of-chance-io = { path = "io" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }

[features]
binary-vendor = []
default = ["binary-vendor"]